version: '3.4'

services:
  travelapp.api:
    container_name: travelapp.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    depends_on:
      - travelappSqldb
    ports:
      - "8003:80"

    volumes:
      - ${HOME}/ASP.NET/Https:/root/.aspnet/https:ro

  travelappSqldb:
    container_name: travelappSqldb 
    ports:
      - "1433:1433" 
    environment:
      SA_PASSWORD: "Odb12345678"
      ACCEPT_EULA: "Y"